# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-11 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailpolls', '0002_auto_20161025_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'poll', 'verbose_name_plural': 'polls'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'vote', 'verbose_name_plural': 'votes'},
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
    ]
